services:
  eavi-college:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=4000
      - NEXT_TELEMETRY_DISABLED=1
      - DATABASE_URL=postgresql://0rmXzAXfHRrZbOuX:kMo0ghHiN9Uqwx4uttaROdk52i0F16iY@127.0.0.1:5432/eavi_college?schema=public
    volumes:
      - ./.env:/app/.env
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./.wwebjs_cache:/app/.wwebjs_cache
      - ./storage:/app/storage
      - ./logs:/app/logs
    restart: unless-stopped