services:
  eavi-college:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "bridge"
    ports:
      - "4000:4000"
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=4000
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./.env:/app/.env
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./.wwebjs_cache:/app/.wwebjs_cache
      - ./storage:/app/storage
      - ./logs:/app/logs
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
    restart: unless-stopped
